const author={name:"Stella Recchia",tagline:"Stories about love, life, and the funny parts in between."};
function Flower({kind="peony"}){return <svg className={"flower "+kind} viewBox="0 0 180 220" aria-hidden="true"><path className="stem" d="M91 215C88 161 101 118 91 73"/><path className="leaf" d="M92 154c-34-22-49-5-53 12 25 8 42 2 53-12ZM94 132c31-26 49-12 55 3-21 13-40 11-55-3Z"/><g className="bloom"><ellipse cx="91" cy="57" rx="28" ry="39"/><ellipse cx="67" cy="66" rx="25" ry="34" transform="rotate(-45 67 66)"/><ellipse cx="115" cy="66" rx="25" ry="34" transform="rotate(45 115 66)"/><ellipse cx="75" cy="43" rx="22" ry="31" transform="rotate(-20 75 43)"/><ellipse cx="107" cy="43" rx="22" ry="31" transform="rotate(20 107 43)"/><circle cx="91" cy="62" r="20"/></g></svg>}
export default function Home(){return <main>
<header><a className="brand" href="#top">{author.name}</a><nav><a href="#about">About</a><a href="#inspiration">Inspiration</a><a href="#working">Working on</a><a href="#contact">Contact</a></nav></header>
<section id="top" className="hero"><div className="sun"></div><Flower/><div className="heroCopy"><p className="eyebrow">ROMANCE · HUMOR · HAPPILY EVER AFTERS</p><h1>Love stories<br/><em>with a little</em><br/>life in them.</h1><p>{author.tagline}</p><a className="button" href="#working">See what I'm writing <span>→</span></a></div><Flower kind="lilac"/><div className="scribble">meet cute →</div></section>
<section id="about" className="about"><div><p className="eyebrow">HELLO, THERE</p><h2>I'm Stella.</h2></div><div><p className="big">I write modern love stories about imperfect people finding something unexpectedly wonderful.</p><p>There are usually complicated feelings, questionable decisions, people who make each other laugh—and, eventually, a happy ending.</p><a className="textlink" href="#">A little more about me →</a></div></section>
<section id="working" className="working"><div className="book"><span>COMING<br/>TO LIFE</span><Flower/></div><div><p className="eyebrow">ON MY DESK</p><h2>Currently<br/><em>writing…</em></h2><h3>An untitled romantic comedy</h3><p>A new story is taking shape. For now, let's just say it involves two people who absolutely do not expect to fall for each other.</p><div className="progress"><i></i></div><small>DRAFT IN PROGRESS · fueled by coffee & optimism</small></div></section>
<section id="inspiration" className="inspiration"><p className="eyebrow">THINGS I LOVE</p><h2>Where stories <em>begin.</em></h2><div className="cards"><article><b>01</b><span>Places</span><p>The streets, rooms, trips and tiny corners that make me wonder: what if?</p></article><article><b>02</b><span>People</span><p>Overheard conversations, unlikely friendships, and the beautiful weirdness of being human.</p></article><article><b>03</b><span>Things</span><p>Books, music, flowers, food—and whatever else is living rent-free in my imagination.</p></article></div></section>
<section id="contact" className="contact"><Flower kind="lilac"/><p className="eyebrow">SAY HELLO</p><h2>Let's keep<br/>in <em>touch.</em></h2><p>For book news, questions, or just to say hello.</p><a className="button dark" href="mailto:hello@example.com">Send me a note →</a></section>
<footer><span>{author.name}</span><small>© 2026 {author.name}. All rights reserved.</small><span>Made with ♥ & probably coffee</span></footer>
</main>}